In [83]:
#p(a/b)=(p(a) * p(b/a)) / p(b) bayes theorm

In [84]:
# have multiple types of naive bayes theorm
# bernoulli naive bayes. usecase-> when ever features and target are following a bernoulli distribution like either 0 is answer or 1 we use bernoulli naive bayes
#multinomial naive bayes usecase-> use when the input is in text format than we will use multinomial naive bayes.
#we convert the text into numerical format using natural language processing NLP.

#gaussian naive bayes. usecase-> this is used when our features are following gaussian distribution like(continuous values) bell curve 
# then we use gaussian naive bayes.
#Gaussian Naive Bayes: X can contain continuous numerical features, but y is still categorical. → Classification so this model is used when categorical target.

#other wise in continues target we use regression models.

# if our dataset have features following both bernoulli and gaussain distribution then we use which is the maximum use.

In [85]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [86]:
from sklearn.datasets import load_iris

In [87]:
x,y=load_iris(return_X_y=True)

In [88]:
from sklearn.model_selection import train_test_split
xtest,xtrain,ytest,ytrain=train_test_split(x,y,test_size=0.3,random_state=0)


In [89]:
xtrain

array([[5.8, 2.8, 5.1, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.3, 0.3],
       [6.7, 3.1, 4.7, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 3.6, 1.4, 0.1],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [5.6, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 2.3, 3.3, 1. ],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2

In [90]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [91]:
gnb.fit(xtrain,ytrain)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [92]:
ypred=gnb.predict(xtest)

In [93]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

[[34  0  0]
 [ 0 30  2]
 [ 0  3 36]]
0.9523809523809523
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.91      0.94      0.92        32
           2       0.95      0.92      0.94        39

    accuracy                           0.95       105
   macro avg       0.95      0.95      0.95       105
weighted avg       0.95      0.95      0.95       105



In [94]:
import seaborn as sns
df=sns.load_dataset('tips')

In [95]:
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [96]:
df['time'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']>

In [97]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
lab=LabelEncoder()
hot_for_size=OneHotEncoder()
hot_for_day=OneHotEncoder() # we can't use same onehot encoder for both day and size as one got trained for only one column.
df['sex']=lab.fit_transform(df['sex'])
df['smoker']=lab.fit_transform(df['smoker'])
df['time']=lab.fit_transform(df['time'])
day=hot_for_day.fit_transform(df[['day']]).toarray() # now we have sparse matrix in the day 
size=hot_for_size.fit_transform(df[['size']]).toarray() # and also size is the sparse matrix of the size.

In [98]:
encoded_day=pd.DataFrame(day,columns=hot_for_day.get_feature_names_out())
encoded_size=pd.DataFrame(size,columns=hot_for_size.get_feature_names_out())

In [99]:
encoded_day

,day_Fri,day_Sat,day_Sun,day_Thur
0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0
...,...,...,...,...
239,0.0,1.0,0.0,0.0
240,0.0,1.0,0.0,0.0
241,0.0,1.0,0.0,0.0
242,0.0,1.0,0.0,0.0


In [100]:
encoded_size

,size_1,size_2,size_3,size_4,size_5,size_6
0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...
239,0.0,0.0,1.0,0.0,0.0,0.0
240,0.0,1.0,0.0,0.0,0.0,0.0
241,0.0,1.0,0.0,0.0,0.0,0.0
242,0.0,1.0,0.0,0.0,0.0,0.0


In [101]:
df=pd.concat([df,encoded_day,encoded_size],axis=True)

In [102]:
df.drop(['day','size'],axis=1,inplace=True)

In [103]:
df.head()

,total_bill,tip,sex,smoker,time,day_Fri,day_Sat,day_Sun,day_Thur,size_1,size_2,size_3,size_4,size_5,size_6
0,16.99,1.01,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,10.34,1.66,1,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,21.01,3.50,1,0,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,23.68,3.31,1,0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,24.59,3.61,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0


In [104]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'time', 'day_Fri', 'day_Sat',
       'day_Sun', 'day_Thur', 'size_1', 'size_2', 'size_3', 'size_4', 'size_5',
       'size_6'],
      dtype='object')

In [105]:
x=df.drop('time',axis=1) # only return columns except time to store in x
y=df['time']

In [106]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

In [107]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
model.fit(xtrain,ytrain)


,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"binarize binarize: float or None, default=0.0Threshold for binarizing (mapping to booleans) of sample features.If None, input is presumed to already consist of binary vectors.",0.0
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [108]:
ypred=model.predict(xtest)

In [109]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

[[55  1]
 [ 5 13]]
0.918918918918919
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        56
           1       0.93      0.72      0.81        18

    accuracy                           0.92        74
   macro avg       0.92      0.85      0.88        74
weighted avg       0.92      0.92      0.92        74



In [110]:
params = {
    'alpha': [0.001, 0.01, 0.1, 1.0, 10.0],
    'fit_prior': [True, False],
    'binarize': [0.0, 0.5]
}


In [ ]:
#hyper tunning
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=5,n_jobs=-1)

In [112]:
grid.fit(xtrain,ytrain)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",BernoulliNB()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'alpha': [0.001, 0.01, ...], 'binarize': [0.0, 0.5], 'fit_prior': [True, False]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candidate is displayed;- >2 : the score is also disp

In [113]:
ypred=grid.predict(xtest)

In [114]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

[[55  1]
 [ 5 13]]
0.918918918918919
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        56
           1       0.93      0.72      0.81        18

    accuracy                           0.92        74
   macro avg       0.92      0.85      0.88        74
weighted avg       0.92      0.92      0.92        74



In [ ]:
#model selection
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(xtrain,ytrain)

,"priors priors: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"var_smoothing var_smoothing: float, default=1e-9Portion of the largest variance of all features that is added tovariances for calculation stability... versionadded:: 0.20",1e-09


In [116]:
ypred=model.predict(xtest)

In [117]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

[[55  1]
 [ 4 14]]
0.9324324324324325
              precision    recall  f1-score   support

           0       0.93      0.98      0.96        56
           1       0.93      0.78      0.85        18

    accuracy                           0.93        74
   macro avg       0.93      0.88      0.90        74
weighted avg       0.93      0.93      0.93        74



In [118]:
params={'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3]} # only important hyperparameter to tune.

In [ ]:
#hyper tunning
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=5,n_jobs=-1)

In [120]:
grid.fit(xtrain,ytrain)

,"estimator estimator: estimator objectThis is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.",GaussianNB()
,"param_grid param_grid: dict or list of dictionariesDictionary with parameters names (`str`) as keys and lists ofparameter settings to try as values, or a list of suchdictionaries, in which case the grids spanned by each dictionaryin the list are explored. This enables searching over any sequenceof parameter settings.","{'var_smoothing': [1e-09, 1e-08, ...]}"
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion ` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.",'accuracy'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``GridSearchCV`` instance.Also for multiple metric evaluation, the attributes ``best_index_``,``best_score_`` and ``best_params_`` will only be available if``refit`` is set and all of them will be determined w.r.t this specificscorer.See ``scoring`` parameter to know more about multiple metricevaluation.See :ref:`sphx_glr_auto_examples_model_selection_plot_grid_search_digits.py`to see how to design a custom selection strategy using a callablevia `refit`.See :ref:`this example`for an example of how to use ``refit=callable`` to balance modelcomplexity and cross-validated score... versionchanged:: 0.20 Support for callable added.",True
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"verbose verbose: intControls the verbosity: the higher, the more messages.- >1 : the computation time for each fold and parameter candidate is displayed;- >2 : the score is also displayed;- >3 : the fold and candidate paramete

In [121]:
ypred=grid.predict(xtest)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(ytest,ypred))
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))

# here gaussian naive bayes was better model as accuracy came 0.93 as well as the feature hav e2 columns with continues values like total_bill and tip so we 
# used better was gaussain as it is used for continues features.

[[55  1]
 [ 4 14]]
0.9324324324324325
              precision    recall  f1-score   support

           0       0.93      0.98      0.96        56
           1       0.93      0.78      0.85        18

    accuracy                           0.93        74
   macro avg       0.93      0.88      0.90        74
weighted avg       0.93      0.93      0.93        74



In [123]:
# First check the target column (y) to decide the type of problem.

# 1. If y is CONTINUOUS (numbers with many possible values)
# Example: price, salary, temperature
# Use REGRESSION models:
# - Linear Regression
# - Ridge/Lasso Regression
# - Random Forest Regressor
# - SVR


# 2. If y is CATEGORICAL (classes)
# Example: 0/1, Yes/No, Cat/Dog
# Use CLASSIFICATION models:
# - Logistic Regression
# - SVM
# - Decision Tree
# - Random Forest
# - Naive Bayes


# For Naive Bayes specifically:

# Gaussian Naive Bayes:
# - y must be categorical (binary or multiclass)
# - X can contain continuous numerical features
# Example:
# X = age, salary, height
# y = disease yes/no
# Use GaussianNB


# Bernoulli Naive Bayes:
# - y must be categorical (binary or multiclass)
# - X features should be binary (0/1)
# Example:
# X = smoker(0/1), gender(0/1), word_present(0/1)
# y = spam/not spam
# Use BernoulliNB


# Multinomial Naive Bayes:
# - y must be categorical
# - X contains counts/frequencies
# Example:
# X = word counts in documents
# y = category of document
# Use MultinomialNB