In [3]:
# numpy are used for array creation one dimension two dimension and so on and perform operation on it and use builtin functions.
import numpy as np
arr1=np.array([1,2,3,4,5])
print(f"Array {arr1}") 
print(f"Array shape: {arr1.shape} ") #shape means in dimension rows or columns # ans (5,) means one dimension if there are two numbers means 2 dimension and so on.
print(f"Array Size: {arr1.size}") # array total elements.
print(f"Array dimension: {arr1.ndim}") #ndim is for array dimension
print(f"Array Item size(can vary based on platform): {arr1.itemsize}") # (size in bytes)
print(f"Array datatype: {arr1.dtype}") # data type

Array [1 2 3 4 5]
Array shape: (5,) 
Array Size: 5
Array dimension: 1
Array Item size(can vary based on platform): 8
Array datatype: int64


In [67]:
import numpy as np
arr2=np.array([1,2,3,4,5,6]) # reshape in that way that the elements can form a proper shape. like here you can't do reshape(3,1) but (3,2) or (2,3) in a way that elements divied in correct order.
print("Array Dimension: ",np.ndim(arr2),"\n",arr2)
arr2=arr2.reshape(2,3)
print("\nArray Reshaped (2,3): And Dimension:",np.ndim(arr2),"\n",arr2)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("\nArray Dimension: ",np.ndim(arr2),"\n",arr2)
arr2=arr2.reshape(5,3) # in order to reshape correctly either your row should match the number of elements in each list or your column. other will be how many list are there. 
print("\nArray Reshaped  ",np.ndim(arr2),"\n",arr2)


Array Dimension:  1 
 [1 2 3 4 5 6]

Array Reshaped (2,3): And Dimension: 2 
 [[1 2 3]
 [4 5 6]]

Array Dimension:  2 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Array Reshaped   2 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [4]:
# we can reshape an array using builtin functions
print(f"Reshaped Array: {arr1.reshape(1,5)}") # why i put 1,5 as there are 5 elements on 1 row thats why we can't do 1,4 as there are 5.
print(f"Array dimension: {arr1.ndim}")
print(f"Reshaped Array: \n {arr1.reshape(5,1)}") # reshape returns a copy it doesn't change the original array. until we store reshaped in arr1.
#arr1=arr1.reshape(5,1) # than it will change the orignal
print(f"Array dimension: {arr1.ndim}")

Reshaped Array: [[1 2 3 4 5]]
Array dimension: 1
Reshaped Array: 
 [[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
Array dimension: 1


In [87]:
# changing dimension
import numpy as np
arr1=np.array([[1,2,3,4,5],[5,6,7,8,9]]) # as there are two closing [] thats why two dimension.
print(f"Array dimension: {arr1.ndim}")
print(f"Array: \n{arr1}")
arr1=np.insert(arr1,2,[10,11,12,13,14],axis=0)
print(arr1)

Array dimension: 2
Array: 
[[1 2 3 4 5]
 [5 6 7 8 9]]
[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print(f"Addition element wise:{arr1+arr2}")
print(f"Subtraction element wise:{arr1-arr2}")
print("Multiplication element wise:",arr1*arr2)
print("Division element wise:",arr1/arr2)

Addition element wise:[ 5  7  9 11 13]
Subtraction element wise:[-3 -3 -3 -3 -3]
Multiplication element wise: [ 4 10 18 28 40]
Division element wise: [0.25       0.4        0.5        0.57142857 0.625     ]


In [ ]:
#universal function that apply to all the elements of the array
# without using any loops functions are applied to whole array this is the advantage of numpy for dealing with large data set very easily and quickly
arr1=np.array([1,2,3,4,5,6])
print("Square root of elements: ",np.sqrt(arr1))
print("Sin of elements: ",np.sin(arr1)) 
print("Logarithmic: ",np.log(arr1))

Square root of elements:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Sin of elements:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Logarithmic:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# accessing array elements using slicing
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1.flatten()) # flat the whole array.
print("Array:\n",arr1)
# accessing 1
print("\n",arr1[0][0])
print("\n Now acessing 7 8 11 12:\n",arr1[1:,2:])
print("\n Now acessing 3 4 7 8:\n",arr1[:2,2:])
print("\n Now acessing 6 7 10 11:\n",arr1[1:,1:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 1

 Now acessing 7 8 11 12:
 [[ 7  8]
 [11 12]]

 Now acessing 3 4 7 8:
 [[3 4]
 [7 8]]

 Now acessing 6 7 10 11:
 [[ 6  7]
 [10 11]]


In [48]:
# modifying array elements
arr1[0,0]=100
print(arr1)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [53]:
# now calculate mean and standard deviation of an array
# also normalize the data ### normalizing the data mean that its arthimatic mean is zero and its standard deviation is 1.
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
normalized=(data-mean)/std_dev
print(normalized) 
print(np.mean(normalized)) # confirming that mean is zero after normalization
print(np.std(normalized))


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999


In [58]:
data=np.array([1,2,3,4,5,6,7,8,9])
mean=np.mean(data)
std_dev=np.std(data)
normalized=(data-mean)/std_dev
print(normalized) 
print(np.mean(normalized)) # confirming that mean is zero after normalization
print(np.std(normalized))
print(np.var(data)) # variance

[-1.54919334 -1.161895   -0.77459667 -0.38729833  0.          0.38729833
  0.77459667  1.161895    1.54919334]
0.0
1.0
6.666666666666667


In [64]:
#logical operation
print(data>5)
print(data[data>5])
print(data[(data>3) & (data <7)])

[False False False False False  True  True  True  True]
[6 7 8 9]
[4 5 6]


In [1]:

import numpy as np
data=np.arange(1,10,2)
data

array([1, 3, 5, 7, 9])

In [1]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[(arr>3) & (arr<12)]) # this type of accessing through a condition is called boolean masking
print(arr[arr>5]) # boolean masking
print("\nAccessing 6 7 10 11:\n",arr[1:,1:3])

[ 4  5  6  7  8  9 10 11]
[ 6  7  8  9 10 11 12]

Accessing 6 7 10 11:
 [[ 6  7]
 [10 11]]


In [94]:
import numpy as np
arr3=np.array([1,2,3,4,5,6])
arr4=np.array([10,20,30,40,50,60])
arr5=np.vstack((arr3,arr4)) # vertically stack the 2 arrays
print("Vertically stacked: \n",arr5)
arr5=np.hstack((arr3,arr4))# horizontally stack the 2 arrays
print("\nHorizontally stacked: \n",arr5)
arr_split=np.split(arr5,2) # vertical split
print("Splitted: \n",arr_split)



Vertically stacked: 
 [[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]]

Horizontally stacked: 
 [ 1  2  3  4  5  6 10 20 30 40 50 60]
Splitted: 
 [array([1, 2, 3, 4, 5, 6]), array([10, 20, 30, 40, 50, 60])]


In [ ]:
# so if you have a large data set and you have to calculate discount on each element .
# First method using for loop (very slow method: as a million of data will take a lot of memory for storing inside a list and calculating discount by traversing..) 

data_new=[100,1000,200,500,300]
discount=10 # 10/100 0.1
final_price=[]
for price in data_new:
    final_price.append(price-(price*discount/100))
print(final_price)

# That was the reason numpy library was created in 2005 for faster traversing without any issue or memory problem without using any loops.
import numpy as np
data_new_arr=np.array(data_new) # but you need to convert any list into array first than it will be usefull.
new_final_price=data_new_arr-(data_new_arr*discount/100)   # faster and more realiable
print(new_final_price)

[90.0, 900.0, 180.0, 450.0, 270.0]
[ 90. 900. 180. 450. 270.]


In [ ]:
# broadcasting : meaning applying operations on arrays
new_ar=np.array([1,2,3,4,5])
print(new_ar*2)
# broadcasting expanding single elements dimension to meet the other array dimensions
new_ar=np.array([[1,2,3],[4,5,6]])
new2_ar=np.array([10,20,30]) # like 10 was expended like 10,10,10 and added to 1,2,3 this i was saying expanding dimensions.
print(new_ar+new2_ar) 


[ 2  4  6  8 10]
[[11 22 33]
 [14 25 36]]


In [7]:
import numpy as np
new_ar=np.array([[1,2,3,4,5],[4,5,6,7,8]])
new2_ar=np.array([10,20])
new_ar=new_ar.reshape(5,2)
print("array: \n",new_ar)
new2_ar=new2_ar.reshape(2,3) # cant reshape until it has more element like 6 for here



array: 
 [[1 2]
 [3 4]
 [5 4]
 [5 6]
 [7 8]]


ValueError: cannot reshape array of size 2 into shape (2,3)

In [8]:
list1=[1,2,3]
list2=[1,2,3]
ans=[x+y for x,y in zip(list1,list2)]
print(ans) # slow as list for large data sets use more memory and for loop are slow.
# using numpy
import numpy as np
list1=np.array(list1)
list2=np.array(list2)
print(list1+list2) #haha

[2, 4, 6]
[2 4 6]


In [10]:
import numpy as np
new_data=np.array([1,2,np.nan,3,np.nan,6])
print(np.isnan(new_data)) # isnan function in numpy is used to find only those elements which are empty in numpy array.

[False False  True False  True False]


In [12]:
# to replace those values 
clean_data=np.nan_to_num(new_data,nan=100) # nan_to_num is used to replace only nan values inside the numpy array.
print(clean_data)

[  1.   2. 100.   3. 100.   6.]


In [15]:
import numpy as np
import pandas as pd
df=pd.read_csv('sales1_data.csv')
df.head()

Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [ ]:
df.isnull().sum() # printing the nan values in each column

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [18]:
df['Sales']=df['Sales'].fillna(df['Sales'].mean())

In [ ]:
df.isnull().sum() # now all null values are replaced by the mean of that column.

Date       0
Product    0
Sales      0
Region     0
dtype: int64

In [ ]:
df
# is there are any positive infinity or negative infinity values than to replace them (np.inf is positve infinity)(-np.inf is negative infinity)
# df=df.replace([np.inf,-np.inf],np.nan,inplace=True)  # currently we are replaceing all infinity values with np.nan .#If you do df = df.replace(...), it updates df. So, inplace=True is not needed in that case.
# df=df.fillna(df.mean(),inplace=True) #inplace=True not needed if you writing df=df.fillna(..)

Date   Product  Sales Region
0   2023-01-01  Product3  738.0   West
1   2023-01-02  Product2  868.0  North
2   2023-01-03  Product2  554.0   West
3   2023-01-04  Product1  618.0  South
4   2023-01-05  Product3  501.0   East
5   2023-01-06  Product1  554.0   West
6   2023-01-07  Product3  339.0  South
7   2023-01-08  Product3  280.0  South
8   2023-01-09  Product2  806.0  North
9   2023-01-10  Product2  816.0  South
10  2023-01-11  Product3  469.0   West
11  2023-01-12  Product3  554.0   East
12  2023-01-13  Product3  554.0   East
13  2023-01-14  Product3  676.0   East
14  2023-01-15  Product1  183.0  South
15  2023-01-16  Product1  424.0  South
16  2023-01-17  Product1  554.0  South
17  2023-01-18  Product1  554.0  South
18  2023-01-19  Product2  124.0  North
19  2023-01-20  Product3  732.0   West
20  2023-01-21  Product2  554.0   West
21  2023-01-22  Product3  296.0   West
22  2023-01-23  Product2  737.0   West
23  2023-01-24  Product3  531.0   East
24  2023-01-25  Product2  834.0  North

In [37]:
import numpy as np
import pandas as pd

data = {
    'A': [1, 2, np.nan, 4],
    'B': [np.inf, 5, -np.inf, 7],
    'C': [8, np.nan, 10, np.inf]
}
dff=pd.DataFrame(data)
dff.to_csv('data_Wth_nan_and_inf.csv',index=False) # this index = false prevent pandas to write row index in the csv file.
dff 


A    B     C
0  1.0  inf   8.0
1  2.0  5.0   NaN
2  NaN -inf  10.0
3  4.0  7.0   inf

In [38]:
dff.isnull().sum()

A    1
B    0
C    1
dtype: int64

In [ ]:
dff=dff.replace((np.inf,-np.inf),np.nan) # we replaced all inf with nan so that we can change all nan at once

In [35]:
dff.isnull().sum()

A    0
B    2
C    2
dtype: int64

In [40]:
dff

A    B     C
0  1.0  NaN   8.0
1  2.0  5.0   NaN
2  NaN  NaN  10.0
3  4.0  7.0   NaN

In [ ]:
dff=dff.fillna(dff.mean()) # this is best function. it replace nan value with the mean of that particular column.

In [43]:
dff

A    B     C
0  1.000000  6.0   8.0
1  2.000000  5.0   9.0
2  2.333333  6.0  10.0
3  4.000000  7.0   9.0

In [49]:
dff['A']=dff['A'].astype(int) # changed the data type of 'A'

In [50]:
dff

A    B     C
0  1  6.0   8.0
1  2  5.0   9.0
2  2  6.0  10.0
3  4  7.0   9.0

In [56]:
print(dff.dtypes)

A      int64
B    float64
C    float64
dtype: object
